server:
  port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


spring:
  main:
    web-application-type: reactive
  application:
    name: sgc-gateway


  cloud:
    gateway:
      routes:
        - id: scgClientMain
          uri: lb://SCG-CLIENT-MAIN
          predicates:
            - Path=/main/**
          filters:
            - RewritePath=/main/?(?<path>.), /api/v1/main/$\{path}
        - id: scgClientOther
          uri: lb://SCG-CLIENT-OTHER
          predicates:
            - Path=/other/**
          filters:
            - RewritePath=/other/?(?<path>.), /api/v1/other/$\{path}