server:
  port: 8081

spring:
  application:
    name: scg-client-main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: scgClientMain
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30


scg:
  client:
    other: http://localhost:8080/other/

bandisnc:
  sso:
    server-url: http://localhost:9091
    client-id: colla-test
    client-secret: bfb0df560e322157de15d8bceabbf0a49ebf94097564a9cc4ab98e90d6669b3e18f1.a3038dfabd9fbd309225bfa5edacaa2fc6241285381ceb77d46e3b67be671531e03d46d69f05c7e6952d4e1aef56f1cec495fb7072343ed1edf894158ea190ec92ccd3ad8fc275af810320d9a7f3ea748a8b14f115e45237d48a568fd2ce
    secret-iv: 35f25caaa31f102dd25e6c8269b8d622
    connection-timeout: 100
