server:
  port: 8082

spring:
  application:
    name: scg-client-other

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: scgClientOther
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30


scg:
  client:
    main: http://localhost:8080/main/